# Generated by Django 5.0.4 on 2024-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=3)),
                ('departure_city', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=3)),
                ('arrival_city', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
            ],
        ),
    ]
